### PR TITLE
[WIP] Mschart2

### PR DESCRIPTION
**Pull request by JanMarvin**
I've crafted a WIP pull request to support writing `mschart` charts to `openxlsx2` sheets while using the worksheet data as source. I have created a `wb_data` object which will ship a data frame and references to the origin of the data in a `wbWorkbook`. This way the code looks still human readable and a lot of the original `mschart` codebase can be used.

```R

# install the pull requests
remotes::install_github("https://github.com/JanMarvin/mschart", ref = "mschart2") # this PR
remotes::install_github("https://github.com/JanMarvin/openxlsx2", ref = "mschart2") # corresponding openxlsx2 PR

library(openxlsx2)
library(mschart)

# write data starting at B2 (just to have something not starting at A1)
wb <- wb_workbook()$add_worksheet()$add_data(x = mtcars, dims = "B2")

# create wb_data object this will tell this mschart from this PR to create a file corresponding to openxlsx2
dat <- wb_data(wb, 1, dims = "B2:E6")

# call ms_scatterplot 
data_plot <- ms_scatterchart(
  data = dat,
  x = "mpg",
  y = c("disp", "hp"),
  labels = c("disp", "hp")
)

# add the scatterplot to the data
wb <- wb %>% 
  wb_add_mschart(dims = "F4:L20", graph = data_plot)
```

Now I need your feedback if you would accept such a PR. I'm aware that I have touched various places, but afaik nothing has been broken along the way.

Once we agree something like this PR is wanted, we can iron out other cornerstones. 
Like reducing the diff or splitting the PR further up.

### CODE REVIEW

**Comment by davidgohel** [comment]
> Now I need your feedback if you would accept such a PR. 

Yes totally. Thank you for your contributions, they are welcome. 

> I'm aware that I have touched various places, but afaik nothing has been broken along the way.

That would be perfect, I will try to review your PR in the following days :)

**Comment by JanMarvin** [comment]
Cool, thanks!

Please let me know if you want to see any changes or have another suggestion for implementation. Basically, I wanted to reduce everything related to `ms_chart` to `mschart()`. This allows using the `wb_data` object I created in `openxlsx2` to provide data and cell information for `mschart`. This way, the places with `wb_data` references are reduced at the expense of a larger `mschart()` function. Any changes should only affect the new `asis` argument or cases where `wb_data` is found.

**Comment by davidgohel** [comment]
Hello, I just reviewed your PR. It looks totally OK to me. Also, I run the officeverse book as a *big* test and nothing broke.

Thanks a lot for your contribution. I am sure you having mschart compatible with Excel is an excellent feature for many users.

**Comment by JanMarvin** [comment]
Wonderful news @davidgohel ! Thanks for reviewing and merging. Could you give me a ping when you're preparing the next CRAN release? The `openxlsx2` PR is ready to be merged as well. Merci beaucoup!

**Comment by davidgohel** [comment]
@JanMarvin yes, I will, thanks

**Comment by davidgohel** [comment]
@JanMarvin "package mschart_0.4.0.tar.gz is on its way to CRAN."

**Pull request merged**
