### PR TITLE
Smoothed series

### PR DESCRIPTION
**Pull request by DavidCamposeco**
Modifies the `ms_chart` object whenever created by the `ms_linechart` function to include a `$smooth` value (default=1) in the` $series_settings` of the object. It also modifies the `series` object generated by the `as_series ` function to return a `smooth` value which it inherits from the one generated by the` ms_linechart`  function. Finally it modifies the xml template associated to line charts in the `ooml_code.ms_linechart` function to include the `<c:smooth val="INTEGER"\>`  tag inserting the property generated by `as_series`. I wrote a simple  `chart_data_smooth` function (and a short documentation) to control the smoothing parameter of each series.

### CODE REVIEW

**Comment by DavidCamposeco** [comment]
Hey, @davidgohel  I added some extra features that I needed and that have been asked for by others (see issue #25) . Love the pkg, ty!

**Comment by davidgohel** [comment]
(Sorry for the delay...)

Thanks, it looks good! I will find time to send that version to CRAN next week.

Before merging, could you add:
- a short explanation in vignette "details" part "Line charts"
- your `person` details in Authors@R (in file DESCRIPTION) with role `ctb`?

Thanks!

**Comment by davidgohel** [comment]
Hi @DavidCamposeco, did you see my message?

**Comment by DavidCamposeco** [comment]
Hey @davidgohel  I think I have added what you asked for. Let me know if anything is missing. Sorry for the delay

**Comment by davidgohel** [comment]
@DavidCamposeco thanks again!

**Pull request merged**
